.Net: Example of prompt PII detection logic with Filters and Microsoft Presidio (#6171)
### Motivation and Context

<!-- Thank you for your contribution to the semantic-kernel repo!
Please help reviewers and future users, providing the following
information:
  1. Why is this change required?
  2. What problem does it solve?
  3. What scenario does it contribute to?
  4. If it fixes an open issue, please link to the issue here.
-->

This example shows how to implement Personal Identifiable Information
(PII) detection logic with Filters using Microsoft Presidio service:
https://github.com/microsoft/presidio.

Example contains two filters:

First filter is responsible for PII detection in prompt by using
Presidio Text Analyzer. If PII is detected, then the prompt won't be
sent to LLM and custom result will be returned after function
invocation.

Example output:
```
Prompt: John Smith has a card 1111 2222 3333 4444
Entity type: CREDIT_CARD. Score: 1
Entity type: PERSON. Score: 0.85
Exception: Prompt contains PII information. Operation is canceled.
```

Second filter is responsible for PII detection in prompt and updating
the prompt by following specified rules before sending it to LLM. This
filter uses Presidio Text Analyzer and Presidio Text Anonymizer.

Example output:
```
LLM instructions: If prompt does not contain first and last name - return 'true'.
Prompt before anonymization : Hello world, my name is Jane Doe. My number is: 034453334
Prompt after anonymization : Hello world, my name is ANONYMIZED. My number is: 
Result: true
```

### Contribution Checklist

<!-- Before submitting this PR, please make sure: -->

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution
Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
and the [pre-submission formatting
script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts)
raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile: