Update InteractWithGraph.tsx - Fix failures caused by break change of stripping off the async suffix from SK functions (#2483)
Fix failures caused by break change of stripping off the async suffix
from SK functions

### Motivation and Context

The auth-api sample doesn't work anymore because of the break change
listed in
https://github.com/freistli/semantic-kernel/blob/main/docs/decisions/0003-support-multiple-native-function-args.md

Updated name selection heuristic to strip off an "Async" suffix for
async methods.


### Description

KernelServer service reports similar errors the sample is calling:

Result: Function 'InvokeFunction', Invocation id
'6dcbc5af-9484-4357-a5ac-c91b585dfac5': An exception was thrown by the
invocation.
Exception: System.AggregateException: One or more errors occurred.
(Function not available: Function not available
emailskill.getmyemailaddressasync)

### Contribution Checklist

<!-- Before submitting this PR, please make sure: -->

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution
Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
and the [pre-submission formatting
script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts)
raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile: